-- V3: Agregar columnas nuevas del merge de main a la base de datos de produccion.
-- Cubre: EventoMensaje (nodos_flujo), nuevas columnas de Mensaje, tabla Correlaciones.
-- Usar IF NOT EXISTS / IF EXISTS para que sea seguro ejecutar multiples veces.
--
-- Ejecutar en produccion:
--   psql -h 127.0.0.1 -U admin -d facimus -f sql/V3__agregar_columnas_evento_mensaje.sql

-- ============================================================
-- 1. Columnas de EventoMensaje en nodos_flujo (SINGLE_TABLE)
-- ============================================================
ALTER TABLE nodos_flujo ADD COLUMN IF NOT EXISTS tipo_evento_mensaje varchar(255);
ALTER TABLE nodos_flujo ADD COLUMN IF NOT EXISTS contenido_evento text;
ALTER TABLE nodos_flujo ADD COLUMN IF NOT EXISTS clave_correlacion_evento varchar(255);
ALTER TABLE nodos_flujo ADD COLUMN IF NOT EXISTS origen_externo boolean DEFAULT false;

-- ============================================================
-- 2. Columnas nuevas en mensajes
-- ============================================================
ALTER TABLE mensajes ADD COLUMN IF NOT EXISTS clave_correlacion varchar(255);
ALTER TABLE mensajes ADD COLUMN IF NOT EXISTS evento_throw_id bigint;
ALTER TABLE mensajes ADD COLUMN IF NOT EXISTS evento_catch_id bigint;
ALTER TABLE mensajes ADD COLUMN IF NOT EXISTS tipo_destino_externo varchar(255);
ALTER TABLE mensajes ADD COLUMN IF NOT EXISTS destino_externo varchar(255);
ALTER TABLE mensajes ADD COLUMN IF NOT EXISTS politica_fallo_notificacion varchar(255);
ALTER TABLE mensajes ADD COLUMN IF NOT EXISTS actividad_error_id bigint;
ALTER TABLE mensajes ADD COLUMN IF NOT EXISTS politica_sin_caso varchar(255) DEFAULT 'DESCARTAR';
ALTER TABLE mensajes ADD COLUMN IF NOT EXISTS activo boolean DEFAULT true;

-- Foreign keys para las nuevas columnas de mensajes (ignorar si ya existen)
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_mensaje_evento_throw') THEN
        ALTER TABLE mensajes ADD CONSTRAINT fk_mensaje_evento_throw
            FOREIGN KEY (evento_throw_id) REFERENCES nodos_flujo(id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_mensaje_evento_catch') THEN
        ALTER TABLE mensajes ADD CONSTRAINT fk_mensaje_evento_catch
            FOREIGN KEY (evento_catch_id) REFERENCES nodos_flujo(id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_mensaje_actividad_error') THEN
        ALTER TABLE mensajes ADD CONSTRAINT fk_mensaje_actividad_error
            FOREIGN KEY (actividad_error_id) REFERENCES nodos_flujo(id);
    END IF;
END $$;

-- ============================================================
-- 3. Tabla correlaciones (nueva entidad)
-- ============================================================
CREATE TABLE IF NOT EXISTS correlaciones (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    criterio varchar(255) NOT NULL,
    mensaje_id bigint NOT NULL UNIQUE,
    empresa_id bigint NOT NULL,
    CONSTRAINT fk_correlacion_mensaje FOREIGN KEY (mensaje_id) REFERENCES mensajes(id),
    CONSTRAINT fk_correlacion_empresa FOREIGN KEY (empresa_id) REFERENCES empresas(id)
);

-- Si contenido_evento existe como OID (por @Lob previo), migrar a TEXT
DO $$
DECLARE
    col_type text;
BEGIN
    SELECT data_type INTO col_type
    FROM information_schema.columns
    WHERE table_name = 'nodos_flujo' AND column_name = 'contenido_evento';

    IF col_type = 'oid' THEN
        ALTER TABLE nodos_flujo ADD COLUMN contenido_evento_tmp text;
        UPDATE nodos_flujo SET contenido_evento_tmp = convert_from(lo_get(contenido_evento), 'UTF8')
            WHERE contenido_evento IS NOT NULL;
        ALTER TABLE nodos_flujo DROP COLUMN contenido_evento;
        ALTER TABLE nodos_flujo RENAME COLUMN contenido_evento_tmp TO contenido_evento;
    END IF;
END $$;
